---
title: "Phenology and Mycorrhizae Manuscript"
author: "Kathryn Wheeler"
date: "11/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load Functions and Variables
```{r}
source('sharedVariables.R')
source('NEON_Data_DownloadAndProcess.R')
```

Download NEON Data

#Single Air Temperature At Various Heights 
```{r}
dataName="NEON_SingleAirTemperature"
NEON_ID='DP1.00002.001'
selectColumns <- c('horizontalPosition','verticalPosition','tempSingleMean','tempSingleExpUncert','finalQF')
inFileName <- "SAAT_30min.csv"

downloadNEONdata(dataName=dataName,NEON_ID=NEON_ID)
combineNEONdata(dataName=dataName,NEON_ID=NEON_ID,selectColumns=selectColumns,
                inFileName=inFileName,dataPath=dataPath)

```

#Triple Air Temperature at Top of Canopy
```{r} 
##Need to redownload!! 
dataName="NEON_TemperatureData"
NEON_ID='DP1.00003.001'
selectColumns <- c('tempTripleMean','finalQF')
inFileName <- "TAAT_30min.csv"
varName <- 'tempTripleMean'

downloadNEONdata(dataName=dataName,NEON_ID=NEON_ID)
combineNEONdata(dataName=dataName,NEON_ID=NEON_ID,selectColumns=selectColumns,
                inFileName=inFileName,dataPath=dataPath)
calculateDailyWeather(dataName=dataName,dataPath=dataPath,varName=varName,funType=mean)
gapFillFromDaymet(dataName=dataName,dataPath=dataPath,varName=varName)

```

#Precipitation
```{r}
dataName="NEON_PrecipitationData"
NEON_ID='DP1.00006.001'
selectColumns <- c('precipBulk','precipExpUncert','precipQF')
inFileName <- c("PRIPRE_30min.csv","SECPRE_30min.csv")
varName <- "precipBulk"

downloadNEONdata(dataName=dataName,NEON_ID=NEON_ID)
combineNEONdata(dataName=dataName,NEON_ID=NEON_ID,selectColumns=selectColumns,
                inFileName=inFileName,dataPath=dataPath)
calculateDailyWeather(dataName=dataName,dataPath=dataPath,varName=varName,funType=sum)
gapFillFromDaymet(dataName=dataName,dataPath=dataPath,varName=varName)

```

#NEON Phenology Observations 
```{r}
source('combineNEONdata_PhenoObs.R')
dataName="NEON_PhenologyObservations"
NEON_ID='DP1.10055.001'

downloadNEONdata(dataName=dataName,NEON_ID=NEON_ID)
combineNEONdata_PhenoObs(saveType=="bySite") #Saved in individual files by site because 1 file was too large 
combineNEONdata_PhenoObs(saveType=="firstOfPhenophase")
combineNEONdata_PhenoObs(saveType = "allOfPhenophase")
```

#Download NEON Soil Microbe Data
```{r}
dataName="NEON_SoilMicrobeComposition"
NEON_ID='DP1.10081.001'
#selectColumns <-
inFileName <- c("mcc_soilSeqVariantMetadata_16S.csv","mcc_soilSeqVariantMetadata_ITS.csv")
#varName <- 

downloadNEONdata(dataName=dataName,NEON_ID=NEON_ID) #Note: I had to modify this function to remove the indices for sites that didn't seem to have data. 
combineNEONdata(dataName=dataName,NEON_ID=NEON_ID,selectColumns=selectColumns,
                inFileName=inFileName,dataPath=dataPath)
```

#Download NEON Soil Physical and Chemical Properties
```{r}
dataName <- "NEON_soilProperties"
if(!file.exists(paste0(dataPath,"/",dataName))){
  dir.create(paste0(dataPath,"/",dataName))
}
NEON_ID <- "DP1.10086.001"
downloadNEONdata(dataName=dataName,NEON_ID=NEON_ID)
#inFileNames <- c(,"sls_soilMoisture","sls_soilpH")
inFileName <- "sls_soilCoreCollection.csv"
selectColumns <- c('plotID','decimalLatitude','decimalLongitude','elevation','standingWaterDepth','horizon',
                   'soilTemp','litterDepth','sampleTopDepth','sampleBottomDepth')
dat1 <- combineNEONdata(dataName=dataName,NEON_ID=NEON_ID,selectColumns=selectColumns,
                inFileName=inFileName,dataPath=dataPath,saveFile = FALSE)

inFileName <- "sls_soilpH.csv"
selectColumns <- c('plotID','horizon','soilInWaterpH','soilInCaClpH','pHSoilInWaterMass','pHWaterVol',
                   'waterpHRatio','pHSoilInCaClMass','pHCaClVol','caclpHRatio')
dat2 <- combineNEONdata(dataName=dataName,NEON_ID=NEON_ID,selectColumns=selectColumns,
                inFileName=inFileName,dataPath=dataPath,saveFile = FALSE)
allDat <- full_join(dat1,dat2,by=c('siteID','collectDate','plotID','horizon'))

inFileName <- "sls_soilMoisture.csv"
selectColumns <- c('plotID','horizon','boatMass','freshMassBoatMass','dryMassBoatMass','soilMoisture','dryMassFraction')
dat3 <- combineNEONdata(dataName=dataName,NEON_ID=NEON_ID,selectColumns=selectColumns,
                inFileName=inFileName,dataPath=dataPath,saveFile = FALSE)
allDat <- full_join(allDat,dat3,by=c('siteID','collectDate','plotID','horizon'))

outFileName <- paste0(dataName,"ALLdata.csv")
write.csv(file=paste0(dataPath,outFileName),allData,row.names = FALSE,quote=FALSE)

```

#Download Photosynthetically active radiation (PAR)
```{r}
dataName="NEON_PAR"
NEON_ID='DP1.00024.001'
if(!file.exists(paste0(dataPath,"/",dataName))){
  dir.create(paste0(dataPath,"/",dataName))
}
# selectColumns <- c('precipBulk','precipExpUncert','precipQF')
# inFileName <- c("PRIPRE_30min.csv","SECPRE_30min.csv")
# varName <- "precipBulk"

downloadNEONdata(dataName=dataName,NEON_ID=NEON_ID)
combineNEONdata(dataName=dataName,NEON_ID=NEON_ID,selectColumns=selectColumns,
                inFileName=inFileName,dataPath=dataPath)


```


#NEON PhenoCam Observations
```{r}
source('determinePhenoCamURLs.R')
source('downloadPhenoCamAndCalculateTransitions.R') #Still need to change to have it save it somewhere

```

